### ISSUE TITLE
bosh-deployment-resource doesn't upload stemcells where the director has 2 different types of cpis

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh-deployment-resource#49]
Here is another multi-cpi stemcell issue we ran into.  Attempting to do a deploy that spans 2 CPIs (requiring 2 different stemcells) bosh-deployment-resource fails with a message like `Stemcell bosh-aws-xen-hvm-ubuntu-trusty-go_agent not defined in deployment manifest`.

Steps to reproduce:
1. Setup a director that uses 2 cpis of different types (e.g. AWS and vsphere)
2. This will require uploading 2 stemcells to the director.
3. However, the deployment manifest will only have one stemcell definitions (something like):
```
stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest
```
4. When executing the deploy bosh-deployment-resource attempts to ensure that all the stemcells and versions uploaded are being used in the manifest but it fails to take into account this multi-CPI scenarios.

Somewhat related to: https://github.com/cloudfoundry/bosh-deployment-resource/issues/47

**Comment by drich10** [comment]
Hi @youngm,

I've been looking into this and I'm having a hard time writing a failing test for this scenario (maybe I'm not understanding it correctly). Given your description above I would expect any attempt to upload 2 stemcells of the same `os` or name to fail. I say this because the section of the [code](https://github.com/cloudfoundry/bosh-deployment-resource/blob/master/bosh/deployment_manifest.go#L42-L73) that handles this is agnostic of which CPI(s) are in play. 

Could you tell me which stemcells and versions were failing? The information fed into this function is determined by the `stemcell.MF` file packaged in a stemcell and the most recent versions of stemcells seem like they would pass through this code _ok_. I'll continue to look at this, but I wanted to give you an update in case my understanding was incorrect.

**Comment by youngm** [comment]
Hi @drich10 ,

It doesn't fail with the stemcell upload. It fails when attempting to set the versions of the stemcell in the deployment manifest prior to deploy.  And it actually only fails when the stemcells are of the same version because there will only be one stemcell referenced in the deployment manifest in that case.  I believe it fails with this error https://github.com/cloudfoundry/bosh-deployment-resource/blob/master/bosh/deployment_manifest.go#L57 .

Does that help at all?

**Comment by youngm** [comment]
@drich10 thanks for looking into this.  I'll attempt to duplicate the situation again and give you the details of stemcell version and a sample manifest and exact error I'm getting.

**Comment by youngm** [comment]
@drich10 Well, I just tested the very configuration that I thought failed before and it seems to be working now.
How embarrassing.  I don't know what was wrong with me when I submitted these last 2 issues.  Sorry for taking up your time looking into it.  Next issue I'll be sure to be super thorough with complete test cases and everything.

Thanks for your help!

**Comment by drich10** [comment]
No problem! I'm just glad everything ended up working for ya. Thanks for double checking and getting back to me 👍 .
